from fastapi import APIRouter

from backend.controllers import application_controller as controller

router = APIRouter()
router.add_api_route("/api/templates", controller.list_sample_templates, methods=["GET"])
router.add_api_route("/api/templates/download/{filename}", controller.download_template, methods=["GET"])
router.add_api_route("/api/students", controller.list_students, methods=["GET"])
router.add_api_route("/api/logs", controller.list_upload_logs, methods=["GET"])
router.add_api_route("/api/export/company-drives", controller.export_company_drives, methods=["GET"])
router.add_api_route("/api/export/drive-results/{drive_id}", controller.export_drive_results, methods=["GET"])
router.add_api_route("/api/export/student-roster", controller.export_student_roster, methods=["GET"])
router.add_api_route("/api/export/user-access", controller.export_user_access, methods=["GET"])
router.add_api_route("/api/student/profile", controller.get_student_profile, methods=["GET"])
router.add_api_route("/api/student/results", controller.get_student_results, methods=["GET"])
router.add_api_route("/api/student/applications", controller.get_student_applications, methods=["GET"])
router.add_api_route("/api/student/apply", controller.apply_student_drive, methods=["POST"])
router.add_api_route("/api/student/analysis", controller.get_student_analysis, methods=["GET"])
router.add_api_route("/api/student/resume-upload", controller.upload_student_resume, methods=["POST"])
router.add_api_route("/api/interventions", controller.list_interventions, methods=["GET"])
router.add_api_route("/api/interventions/students", controller.list_intervention_students, methods=["GET"])
router.add_api_route("/api/interventions/{student_id}", controller.get_student_interventions, methods=["GET"])
router.add_api_route("/api/interventions/generate", controller.generate_intervention, methods=["POST"])
router.add_api_route("/api/interventions/generate-all", controller.generate_all_interventions, methods=["POST"])
router.add_api_route("/api/interventions/{intervention_id}/status", controller.change_intervention_status, methods=["PATCH"])
router.add_api_route("/api/intervention/actions/{action_id}", controller.change_intervention_action, methods=["PATCH"])
router.add_api_route("/api/mentor/demo/mentees", controller.get_mentor_demo_data, methods=["GET"])
router.add_api_route("/api/mentor/notes", controller.get_notes, methods=["GET"])
router.add_api_route("/api/mentor/notes", controller.create_note, methods=["POST"])
router.add_api_route("/api/mentor/notes/{note_id}", controller.update_note, methods=["PUT"])
router.add_api_route("/api/mentor/notes/{note_id}", controller.delete_note, methods=["DELETE"])
router.add_api_route("/api/department/dashboard", controller.get_department_dashboard, methods=["GET"])
